test:
	nasm -f bin boot.asm -o boot.bin
	nasm -f bin test_kernel.asm -o test_kernel.bin
	dd if=/dev/zero of=test.img bs=512 count=2880 2>/dev/null
	dd if=boot.bin of=test.img bs=512 count=1 conv=notrunc 2>/dev/null
	dd if=test_kernel.bin of=test.img bs=512 seek=1 conv=notrunc 2>/dev/null
	@echo "Test image created. Run with: qemu-system-i386 -fda test.img"

test-run: test
	qemu-system-i386 -fda test.img
